# Generated by Django 5.2.7 on 2025-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('handbags', 'Handbags'), ('sunglasses', 'Sunglasses'), ('watches', 'Watches'), ('jewellery', 'Jewellery'), ('men_shirts', 'Men Shirts'), ('men_jeans', 'Men Jeans'), ('men_jackets', 'Men Jackets'), ('men_shoes', 'Men Shoes'), ('women_dresses', 'Women Dresses'), ('women_tops', 'Women Tops'), ('women_jeans', 'Women Jeans'), ('women_sarees', 'Women Sarees'), ('kids_tshirts', 'Kids T-Shirts'), ('kids_pants', 'Kids Pants'), ('kids_shoes', 'Kids Shoes'), ('kids_toys', 'Kids Toys')], max_length=50, null=True),
        ),
    ]
